from app.elastic.client import ElasticsearchClient
from app.elastic.configuration import (
    GENERAL_ELASTICSEARCH_INDEX_NAME,
    GENERAL_ELASTICSEARCH_INDEX_SETTINGS,
    GENERAL_ELASTICSEARCH_INDEX_MAPPINGS,
    RECRUITMENT_ELASTICSEARCH_INDEX_NAME,
    RECRUITMENT_ELASTICSEARCH_INDEX_SETTINGS,
    RECRUITMENT_ELASTICSEARCH_INDEX_MAPPINGS,
    SCIENTIFIC_ELASTICSEARCH_INDEX_NAME,
    SCIENTIFIC_ELASTICSEARCH_INDEX_SETTINGS,
    SCIENTIFIC_ELASTICSEARCH_INDEX_MAPPINGS
)

EsClient = ElasticsearchClient()

__all__ = [
    "GENERAL_ELASTICSEARCH_INDEX_NAME",
    "GENERAL_ELASTICSEARCH_INDEX_SETTINGS",
    "GENERAL_ELASTICSEARCH_INDEX_MAPPINGS",
    "RECRUITMENT_ELASTICSEARCH_INDEX_NAME",
    "RECRUITMENT_ELASTICSEARCH_INDEX_SETTINGS",
    "RECRUITMENT_ELASTICSEARCH_INDEX_MAPPINGS",
    "SCIENTIFIC_ELASTICSEARCH_INDEX_NAME",
    "SCIENTIFIC_ELASTICSEARCH_INDEX_SETTINGS",
    "SCIENTIFIC_ELASTICSEARCH_INDEX_MAPPINGS",
]