"""add column refresh token and valid until

Revision ID: 02c49a0e3266
Revises: 8210fd97a82e
Create Date: 2023-03-16 15:17:11.574463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c49a0e3266'
down_revision = '8210fd97a82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token_valid_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_valid_until')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
