"""add size to document table

Revision ID: 0a87bdcb16d7
Revises: d94665ef3b83
Create Date: 2023-04-28 16:56:07.950433

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a87bdcb16d7"
down_revision = "d94665ef3b83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("size", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "size")
    # ### end Alembic commands ###
