"""cek migration

Revision ID: 1b884479238c
Revises: 4f84fbf3af30
Create Date: 2023-05-01 02:41:47.601036

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b884479238c"
down_revision = "4f84fbf3af30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_indexes", "reason")
    op.add_column("document_indexes", sa.Column("reason", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_indexes", "reason")
    op.add_column("document_indexes", sa.Column("reason", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
