"""Added document table v1

Revision ID: 34c61696006e
Revises: 02c49a0e3266
Create Date: 2023-04-03 11:58:05.320420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34c61696006e"
down_revision = "68b84e326d41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("elastic_doc_id", sa.Unicode(length=255), nullable=True),
        sa.Column("elastic_index_name", sa.Unicode(length=255), nullable=True),
        sa.Column("title", sa.Unicode(length=255), nullable=False),
        sa.Column("doc_created_at", sa.DateTime(), nullable=True),
        sa.Column("doc_updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_indexes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("doc_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "READY",
                "PARSING",
                "EXTRACTING",
                "INDEXING",
                "SUCCESS",
                "FAILED",
                name="indexingstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.TEXT, nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_indexes")
    op.drop_table("documents")
    op.execute("DROP TYPE indexingstatusenum")
    # ### end Alembic commands ###
