"""sync document and others

Revision ID: 41eca3d0460e
Revises: 849827b9132e
Create Date: 2023-04-25 22:22:17.285040

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "41eca3d0460e"
down_revision = "849827b9132e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_indexes",
        sa.Column("current_task_id", sa.Unicode(length=255), nullable=True),
    )
    op.add_column("documents", sa.Column("file_content_str", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_content_str")
    op.drop_column("document_indexes", "current_task_id")
    # ### end Alembic commands ###
