"""add file url in documents table

Revision ID: 54f1cdd589ba
Revises: 5f1f5bc6b44e
Create Date: 2023-04-21 12:15:48.957997

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "54f1cdd589ba"
down_revision = "5f1f5bc6b44e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_url", sa.Unicode(length=255), nullable=False)
    )
    op.drop_column("documents", "doc_created_at")
    op.drop_column("documents", "doc_updated_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "doc_updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "doc_created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("documents", "file_url")
    # ### end Alembic commands ###
