"""create repositories table

Revision ID: 5d4c42ea0097
Revises: 34c61696006e
Create Date: 2023-04-11 16:41:14.488611

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d4c42ea0097"
down_revision = "34c61696006e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Unicode(length=255), nullable=False),
        sa.Column("description", sa.Unicode(length=255), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("repositories")
    # ### end Alembic commands ###
