"""add otp and forgot password otp columns in users table


Revision ID: 68b84e326d41
Revises: 02c49a0e3266
Create Date: 2023-03-28 03:14:57.828651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68b84e326d41"
down_revision = "02c49a0e3266"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("otp", sa.Unicode(length=255), nullable=True))
    op.add_column("users", sa.Column("otp_valid_until", sa.DateTime(), nullable=True))
    op.add_column(
        "users", sa.Column("forgot_password_otp", sa.Unicode(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("forgot_password_otp_valid_until", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "forgot_password_otp_valid_until")
    op.drop_column("users", "forgot_password_otp")
    op.drop_column("users", "otp_valid_until")
    op.drop_column("users", "otp")
    # ### end Alembic commands ###
