"""fixed indexing status enum

Revision ID: 70363c29098f
Revises: 1b884479238c
Create Date: 2023-05-01 03:14:40.793297

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70363c29098f"
down_revision = "1b884479238c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_indexes", "status")
    op.add_column(
        "document_indexes",
        sa.Column(
            "status",
            sa.Enum(
                "READY",
                "PARSING",
                "EXTRACTING",
                "INDEXING",
                "SUCCESS",
                "FAILED",
                name="indexingstatusenum",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_indexes", "status")
    op.add_column(
        "document_indexes",
        sa.Column(
            "status",
            sa.Enum(
                "READY",
                "PARSING",
                "EXTRACTING",
                "INDEXING",
                "SUCCESS",
                "FAILED",
                name="indexingstatusenum",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
