"""add repository id in documents table

Revision ID: 849827b9132e
Revises: 54f1cdd589ba
Create Date: 2023-04-22 13:52:03.661952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "849827b9132e"
down_revision = "54f1cdd589ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("repository_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(None, "documents", "repositories", ["repository_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "repository_id")
    # ### end Alembic commands ###
