"""change elastic doc id data type

Revision ID: a5cfefb4e79c
Revises: 41eca3d0460e
Create Date: 2023-04-26 01:04:12.111315

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5cfefb4e79c"
down_revision = "41eca3d0460e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "elastic_doc_id")
    sa.Column("elastic_doc_id", sa.Unicode(length=255), nullable=True),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "elastic_doc_id")
    sa.Column("elastic_doc_id", sa.Integer(), nullable=True),
    # ### end Alembic commands ###
