"""Add temporary long text str

Revision ID: b89cf41b64d7
Revises: a7375ff9e955
Create Date: 2023-04-22 21:06:39.830765

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b89cf41b64d7"
down_revision = "a7375ff9e955"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("file_content_str", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_content_str")
    # ### end Alembic commands ###
