name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - '.github/**'
  push:
    
  jobs:
    build:
      runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Docker login
        run: docker login ghcr.io --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: docker build -f Dockerfile -t ghcr.io/IRySTeam/IRyS-BE:latest .
      - name: Push image
        run: docker push ghcr.io/IRySTeam/IRyS-BE:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Deploy Using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.DEV_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~
          docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker-compose down
          docker rmi -f $(docker images -aq)
          docker-compose up 
